version: '3.8'

services:
  background-remover-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - PORT=5000
      - MAX_FILE_SIZE=10485760
    volumes:
      - model_cache:/root/.u2net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  model_cache: